CE103 Homework 4 Duygu Ayvaz Hayrunnisa Kasimay: ce103_hw4_medical_store_lib.Medicine Class Reference
ce103_hw4_medical_store_lib.Medicine Class Reference
Public Member Functions
int getId ()
void setId (int id)
String getMedicinename ()
void setMedicinename (String medicinename)
String getRackno ()
void setRackno (String rackno)
String getCabnitno ()
void setCabnitno (String cabnitno)
String getCompanyname ()
void setCompanyname (String companyname)
String getSuppliername ()
void setSuppliername (String suppliername)
int getUnitcost ()
void setUnitcost (int unitcost)
int getSalecost ()
void setSalecost (int salecost)
int getQuantity ()
void setQuantity (int quantity)
int getMfgdate ()
void setMfgdate (int mfgdate)
String getExpdate ()
void setExpdate (String expdate)
Static Public Member Functions
static byte[] medicineToByteArrayBlock (Medicine book)
static Medicine ByteArrayBlockToMedicine (byte[] byteArray)
Static Public Attributes
static final int ID_LENGTH = 4
static final int MEDICINENAME_MAX_LENGTH = 25
static final int RACKNO_MAX_LENGTH = 9
static final int CABNITNO_MAX_LENGTH = 25
static final int COMPANYNAME_MAX_LENGTH = 25
static final int SUPPLIERNAME_MAX_LENGTH = 25
static final int MFGDATE_MAX_LENGTH = 10
static final int EXPDATE_MAX_LENGTH = 10
static final int UNITCOST_LENGTH = 9
static final int SALECOST_LENGTH = 9
static final int QUANTITY_LENGTH = 9
static final int MEDICINE_DATA_BLOCK_SIZE = ID_LENGTH +MEDICINENAME_MAX_LENGTH+UNITCOST_LENGTH+SALECOST_LENGTH+QUANTITY_LENGTH +RACKNO_MAX_LENGTH+CABNITNO_MAX_LENGTH+COMPANYNAME_MAX_LENGTH+SUPPLIERNAME_MAX_LENGTH+MFGDATE_MAX_LENGTH+EXPDATE_MAX_LENGTH
Member Function Documentation
ByteArrayBlockToMedicine()
static Medicine ce103_hw4_medical_store_lib.Medicine.ByteArrayBlockToMedicine (byte[] byteArray) static
References ce103_hw4_medical_store_lib.ConversionUtility.byteArrayToInteger(), ce103_hw4_medical_store_lib.ConversionUtility.byteArrayToString(), ce103_hw4_medical_store_lib.Medicine.CABNITNO_MAX_LENGTH, ce103_hw4_medical_store_lib.Medicine.COMPANYNAME_MAX_LENGTH, ce103_hw4_medical_store_lib.Medicine.EXPDATE_MAX_LENGTH, ce103_hw4_medical_store_lib.Medicine.ID_LENGTH, ce103_hw4_medical_store_lib.Medicine.MEDICINE_DATA_BLOCK_SIZE, ce103_hw4_medical_store_lib.Medicine.MEDICINENAME_MAX_LENGTH, ce103_hw4_medical_store_lib.Medicine.MFGDATE_MAX_LENGTH, ce103_hw4_medical_store_lib.Medicine.QUANTITY_LENGTH, ce103_hw4_medical_store_lib.Medicine.RACKNO_MAX_LENGTH, ce103_hw4_medical_store_lib.Medicine.SALECOST_LENGTH, ce103_hw4_medical_store_lib.Medicine.setCabnitno(), ce103_hw4_medical_store_lib.Medicine.setCompanyname(), ce103_hw4_medical_store_lib.Medicine.setExpdate(), ce103_hw4_medical_store_lib.Medicine.setId(), ce103_hw4_medical_store_lib.Medicine.setMedicinename(), ce103_hw4_medical_store_lib.Medicine.setQuantity(), ce103_hw4_medical_store_lib.Medicine.setRackno(), ce103_hw4_medical_store_lib.Medicine.setSalecost(), ce103_hw4_medical_store_lib.Medicine.setSuppliername(), ce103_hw4_medical_store_lib.Medicine.setUnitcost(), ce103_hw4_medical_store_lib.Medicine.SUPPLIERNAME_MAX_LENGTH, and ce103_hw4_medical_store_lib.Medicine.UNITCOST_LENGTH.
Referenced by ce103_hw4_medical_store_app.InsiderOfTheMenu.listmedicine(), ce103_hw4_medical_store_app.InsiderOfTheMenu.salemedicine(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.stockmedicine().
getCabnitno()
String ce103_hw4_medical_store_lib.Medicine.getCabnitno ()
Referenced by ce103_hw4_medical_store_app.InsiderOfTheMenu.listmedicine(), ce103_hw4_medical_store_lib.Medicine.medicineToByteArrayBlock(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.salemedicine().
getCompanyname()
String ce103_hw4_medical_store_lib.Medicine.getCompanyname ()
Referenced by ce103_hw4_medical_store_app.InsiderOfTheMenu.listmedicine(), ce103_hw4_medical_store_lib.Medicine.medicineToByteArrayBlock(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.salemedicine().
getExpdate()
String ce103_hw4_medical_store_lib.Medicine.getExpdate ()
Referenced by ce103_hw4_medical_store_app.InsiderOfTheMenu.listmedicine(), ce103_hw4_medical_store_lib.Medicine.medicineToByteArrayBlock(), ce103_hw4_medical_store_app.InsiderOfTheMenu.salemedicine(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.stockmedicine().
getId()
int ce103_hw4_medical_store_lib.Medicine.getId ()
Referenced by ce103_hw4_medical_store_app.InsiderOfTheMenu.listmedicine(), ce103_hw4_medical_store_lib.Medicine.medicineToByteArrayBlock(), ce103_hw4_medical_store_app.InsiderOfTheMenu.salemedicine(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.stockmedicine().
getMedicinename()
String ce103_hw4_medical_store_lib.Medicine.getMedicinename ()
Referenced by ce103_hw4_medical_store_app.InsiderOfTheMenu.listmedicine(), ce103_hw4_medical_store_lib.Medicine.medicineToByteArrayBlock(), ce103_hw4_medical_store_app.InsiderOfTheMenu.salemedicine(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.stockmedicine().
getMfgdate()
int ce103_hw4_medical_store_lib.Medicine.getMfgdate ()
Referenced by ce103_hw4_medical_store_app.InsiderOfTheMenu.listmedicine(), ce103_hw4_medical_store_lib.Medicine.medicineToByteArrayBlock(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.salemedicine().
getQuantity()
int ce103_hw4_medical_store_lib.Medicine.getQuantity ()
Referenced by ce103_hw4_medical_store_app.InsiderOfTheMenu.listmedicine(), ce103_hw4_medical_store_lib.Medicine.medicineToByteArrayBlock(), ce103_hw4_medical_store_app.InsiderOfTheMenu.salemedicine(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.stockmedicine().
getRackno()
String ce103_hw4_medical_store_lib.Medicine.getRackno ()
Referenced by ce103_hw4_medical_store_app.InsiderOfTheMenu.listmedicine(), ce103_hw4_medical_store_lib.Medicine.medicineToByteArrayBlock(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.salemedicine().
getSalecost()
int ce103_hw4_medical_store_lib.Medicine.getSalecost ()
Referenced by ce103_hw4_medical_store_app.InsiderOfTheMenu.listmedicine(), ce103_hw4_medical_store_lib.Medicine.medicineToByteArrayBlock(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.salemedicine().
getSuppliername()
String ce103_hw4_medical_store_lib.Medicine.getSuppliername ()
Referenced by ce103_hw4_medical_store_app.InsiderOfTheMenu.listmedicine(), ce103_hw4_medical_store_lib.Medicine.medicineToByteArrayBlock(), ce103_hw4_medical_store_app.InsiderOfTheMenu.salemedicine(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.stockmedicine().
getUnitcost()
int ce103_hw4_medical_store_lib.Medicine.getUnitcost ()
Referenced by ce103_hw4_medical_store_app.InsiderOfTheMenu.listmedicine(), ce103_hw4_medical_store_lib.Medicine.medicineToByteArrayBlock(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.salemedicine().
medicineToByteArrayBlock()
static byte[] ce103_hw4_medical_store_lib.Medicine.medicineToByteArrayBlock (Medicine book) static
References ce103_hw4_medical_store_lib.Medicine.CABNITNO_MAX_LENGTH, ce103_hw4_medical_store_lib.Medicine.COMPANYNAME_MAX_LENGTH, ce103_hw4_medical_store_lib.Medicine.EXPDATE_MAX_LENGTH, ce103_hw4_medical_store_lib.Medicine.getCabnitno(), ce103_hw4_medical_store_lib.Medicine.getCompanyname(), ce103_hw4_medical_store_lib.Medicine.getExpdate(), ce103_hw4_medical_store_lib.Medicine.getId(), ce103_hw4_medical_store_lib.Medicine.getMedicinename(), ce103_hw4_medical_store_lib.Medicine.getMfgdate(), ce103_hw4_medical_store_lib.Medicine.getQuantity(), ce103_hw4_medical_store_lib.Medicine.getRackno(), ce103_hw4_medical_store_lib.Medicine.getSalecost(), ce103_hw4_medical_store_lib.Medicine.getSuppliername(), ce103_hw4_medical_store_lib.Medicine.getUnitcost(), ce103_hw4_medical_store_lib.Medicine.ID_LENGTH, ce103_hw4_medical_store_lib.ConversionUtility.integerToByteArray(), ce103_hw4_medical_store_lib.Medicine.MEDICINE_DATA_BLOCK_SIZE, ce103_hw4_medical_store_lib.Medicine.MEDICINENAME_MAX_LENGTH, ce103_hw4_medical_store_lib.Medicine.MFGDATE_MAX_LENGTH, ce103_hw4_medical_store_lib.Medicine.QUANTITY_LENGTH, ce103_hw4_medical_store_lib.Medicine.RACKNO_MAX_LENGTH, ce103_hw4_medical_store_lib.Medicine.SALECOST_LENGTH, ce103_hw4_medical_store_lib.ConversionUtility.stringToByteArray(), ce103_hw4_medical_store_lib.Medicine.SUPPLIERNAME_MAX_LENGTH, and ce103_hw4_medical_store_lib.Medicine.UNITCOST_LENGTH.
Referenced by ce103_hw4_medical_store_app.InsiderOfTheMenu.purchasemedicine(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.salemedicine().
setCabnitno()
void ce103_hw4_medical_store_lib.Medicine.setCabnitno (String cabnitno)
Referenced by ce103_hw4_medical_store_lib.Medicine.ByteArrayBlockToMedicine(), ce103_hw4_medical_store_app.InsiderOfTheMenu.purchasemedicine(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.salemedicine().
setCompanyname()
void ce103_hw4_medical_store_lib.Medicine.setCompanyname (String companyname)
Referenced by ce103_hw4_medical_store_lib.Medicine.ByteArrayBlockToMedicine(), ce103_hw4_medical_store_app.InsiderOfTheMenu.purchasemedicine(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.salemedicine().
setExpdate()
void ce103_hw4_medical_store_lib.Medicine.setExpdate (String expdate)
Referenced by ce103_hw4_medical_store_lib.Medicine.ByteArrayBlockToMedicine(), ce103_hw4_medical_store_app.InsiderOfTheMenu.purchasemedicine(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.salemedicine().
setId()
void ce103_hw4_medical_store_lib.Medicine.setId (int id)
Referenced by ce103_hw4_medical_store_lib.Medicine.ByteArrayBlockToMedicine(), ce103_hw4_medical_store_app.InsiderOfTheMenu.purchasemedicine(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.salemedicine().
setMedicinename()
void ce103_hw4_medical_store_lib.Medicine.setMedicinename (String medicinename)
Referenced by ce103_hw4_medical_store_lib.Medicine.ByteArrayBlockToMedicine(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.salemedicine().
setMfgdate()
void ce103_hw4_medical_store_lib.Medicine.setMfgdate (int mfgdate)
Referenced by ce103_hw4_medical_store_app.InsiderOfTheMenu.purchasemedicine(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.salemedicine().
setQuantity()
void ce103_hw4_medical_store_lib.Medicine.setQuantity (int quantity)
Referenced by ce103_hw4_medical_store_lib.Medicine.ByteArrayBlockToMedicine(), ce103_hw4_medical_store_app.InsiderOfTheMenu.purchasemedicine(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.salemedicine().
setRackno()
void ce103_hw4_medical_store_lib.Medicine.setRackno (String rackno)
Referenced by ce103_hw4_medical_store_lib.Medicine.ByteArrayBlockToMedicine(), ce103_hw4_medical_store_app.InsiderOfTheMenu.purchasemedicine(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.salemedicine().
setSalecost()
void ce103_hw4_medical_store_lib.Medicine.setSalecost (int salecost)
Referenced by ce103_hw4_medical_store_lib.Medicine.ByteArrayBlockToMedicine(), ce103_hw4_medical_store_app.InsiderOfTheMenu.purchasemedicine(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.salemedicine().
setSuppliername()
void ce103_hw4_medical_store_lib.Medicine.setSuppliername (String suppliername)
Referenced by ce103_hw4_medical_store_lib.Medicine.ByteArrayBlockToMedicine(), ce103_hw4_medical_store_app.InsiderOfTheMenu.purchasemedicine(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.salemedicine().
setUnitcost()
void ce103_hw4_medical_store_lib.Medicine.setUnitcost (int unitcost)
Referenced by ce103_hw4_medical_store_lib.Medicine.ByteArrayBlockToMedicine(), ce103_hw4_medical_store_app.InsiderOfTheMenu.purchasemedicine(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.salemedicine().
Member Data Documentation
CABNITNO_MAX_LENGTH
final int ce103_hw4_medical_store_lib.Medicine.CABNITNO_MAX_LENGTH = 25 static
Referenced by ce103_hw4_medical_store_lib.Medicine.ByteArrayBlockToMedicine(), and ce103_hw4_medical_store_lib.Medicine.medicineToByteArrayBlock().
COMPANYNAME_MAX_LENGTH
final int ce103_hw4_medical_store_lib.Medicine.COMPANYNAME_MAX_LENGTH = 25 static
Referenced by ce103_hw4_medical_store_lib.Medicine.ByteArrayBlockToMedicine(), and ce103_hw4_medical_store_lib.Medicine.medicineToByteArrayBlock().
EXPDATE_MAX_LENGTH
final int ce103_hw4_medical_store_lib.Medicine.EXPDATE_MAX_LENGTH = 10 static
Referenced by ce103_hw4_medical_store_lib.Medicine.ByteArrayBlockToMedicine(), and ce103_hw4_medical_store_lib.Medicine.medicineToByteArrayBlock().
ID_LENGTH
final int ce103_hw4_medical_store_lib.Medicine.ID_LENGTH = 4 static
Referenced by ce103_hw4_medical_store_lib.Medicine.ByteArrayBlockToMedicine(), and ce103_hw4_medical_store_lib.Medicine.medicineToByteArrayBlock().
MEDICINE_DATA_BLOCK_SIZE
final int ce103_hw4_medical_store_lib.Medicine.MEDICINE_DATA_BLOCK_SIZE = ID_LENGTH +MEDICINENAME_MAX_LENGTH+UNITCOST_LENGTH+SALECOST_LENGTH+QUANTITY_LENGTH +RACKNO_MAX_LENGTH+CABNITNO_MAX_LENGTH+COMPANYNAME_MAX_LENGTH+SUPPLIERNAME_MAX_LENGTH+MFGDATE_MAX_LENGTH+EXPDATE_MAX_LENGTH static
Referenced by ce103_hw4_medical_store_lib.Medicine.ByteArrayBlockToMedicine(), ce103_hw4_medical_store_app.InsiderOfTheMenu.listmedicine(), ce103_hw4_medical_store_lib.Medicine.medicineToByteArrayBlock(), ce103_hw4_medical_store_app.InsiderOfTheMenu.salemedicine(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.stockmedicine().
MEDICINENAME_MAX_LENGTH
final int ce103_hw4_medical_store_lib.Medicine.MEDICINENAME_MAX_LENGTH = 25 static
Referenced by ce103_hw4_medical_store_lib.Medicine.ByteArrayBlockToMedicine(), and ce103_hw4_medical_store_lib.Medicine.medicineToByteArrayBlock().
MFGDATE_MAX_LENGTH
final int ce103_hw4_medical_store_lib.Medicine.MFGDATE_MAX_LENGTH = 10 static
Referenced by ce103_hw4_medical_store_lib.Medicine.ByteArrayBlockToMedicine(), and ce103_hw4_medical_store_lib.Medicine.medicineToByteArrayBlock().
QUANTITY_LENGTH
final int ce103_hw4_medical_store_lib.Medicine.QUANTITY_LENGTH = 9 static
Referenced by ce103_hw4_medical_store_lib.Medicine.ByteArrayBlockToMedicine(), and ce103_hw4_medical_store_lib.Medicine.medicineToByteArrayBlock().
RACKNO_MAX_LENGTH
final int ce103_hw4_medical_store_lib.Medicine.RACKNO_MAX_LENGTH = 9 static
Referenced by ce103_hw4_medical_store_lib.Medicine.ByteArrayBlockToMedicine(), and ce103_hw4_medical_store_lib.Medicine.medicineToByteArrayBlock().
SALECOST_LENGTH
final int ce103_hw4_medical_store_lib.Medicine.SALECOST_LENGTH = 9 static
Referenced by ce103_hw4_medical_store_lib.Medicine.ByteArrayBlockToMedicine(), and ce103_hw4_medical_store_lib.Medicine.medicineToByteArrayBlock().
SUPPLIERNAME_MAX_LENGTH
final int ce103_hw4_medical_store_lib.Medicine.SUPPLIERNAME_MAX_LENGTH = 25 static
Referenced by ce103_hw4_medical_store_lib.Medicine.ByteArrayBlockToMedicine(), and ce103_hw4_medical_store_lib.Medicine.medicineToByteArrayBlock().
UNITCOST_LENGTH
final int ce103_hw4_medical_store_lib.Medicine.UNITCOST_LENGTH = 9 static
Referenced by ce103_hw4_medical_store_lib.Medicine.ByteArrayBlockToMedicine(), and ce103_hw4_medical_store_lib.Medicine.medicineToByteArrayBlock().
The documentation for this class was generated from the following file:
Medicine.java