CE103 Homework 4 Duygu Ayvaz Hayrunnisa Kasimay: ce103_hw4_medical_store_lib.ConversionUtility Class Reference
ce103_hw4_medical_store_lib.ConversionUtility Class Reference
Static Public Member Functions
static Byte[] toByte (String hexString)
static String toHex (byte[] arr)
static boolean isHex (String str)
static Byte[] toByteArray (String hexString)
static int getInt (byte[] data, int offset, int length)
static String toAscii (String hexString)
static int byteArrayToInteger (byte[] byteArray)
static byte[] integerToByteArray (int value)
static byte[] stringListToByteArray (List< String > array, int itemMaxCount, int itemMaxLength)
static List< String > byteArrayToStringList (byte[] byteArray, int itemMaxCount, int itemMaxLength)
static byte[] stringToByteArray (String data)
static String byteArrayToString (byte[] byteArray)
Member Function Documentation
byteArrayToInteger()
static int ce103_hw4_medical_store_lib.ConversionUtility.byteArrayToInteger (byte[] byteArray) static
Converts a byte array to an integer.
Parameters
byteArray The byte array to convert.
Returns
The integer value stored in the byte array.
Referenced by ce103_hw4_medical_store_lib.Bill.byteArrayBlockToBook(), ce103_hw4_medical_store_lib.Customer.ByteArrayBlockToCustomer(), ce103_hw4_medical_store_lib.Medicine.ByteArrayBlockToMedicine(), and ce103_hw4_medical_store_lib.Supplier.byteArrayBlockToSupplier().
byteArrayToString()
static String ce103_hw4_medical_store_lib.ConversionUtility.byteArrayToString (byte[] byteArray) static
Converts a byte array to a string.
Parameters
byteArray The byte array to convert.
Returns
The string stored in the byte array.
Referenced by ce103_hw4_medical_store_lib.Bill.byteArrayBlockToBook(), ce103_hw4_medical_store_lib.Customer.ByteArrayBlockToCustomer(), ce103_hw4_medical_store_lib.Medicine.ByteArrayBlockToMedicine(), and ce103_hw4_medical_store_lib.Supplier.byteArrayBlockToSupplier().
byteArrayToStringList()
static List< String > ce103_hw4_medical_store_lib.ConversionUtility.byteArrayToStringList (byte[] byteArray, int itemMaxCount, int itemMaxLength) static
Converts a byte array to a list of strings.
Parameters
byteArray The byte array to convert.
itemMaxCount The maximum number of items in the list.
itemMaxLength The maximum length of each item in the list.
Returns
The list of strings stored in the byte array.
getInt()
static int ce103_hw4_medical_store_lib.ConversionUtility.getInt (byte[] data, int offset, int length) static
Extracts an integer value from an array of bytes.
Parameters
data The array of bytes from which to extract the integer value.
offset The starting position in the array from which to extract the integer value.
length The number of bytes to use in the extraction.
Returns
The integer value extracted from the array of bytes.
integerToByteArray()
static byte[] ce103_hw4_medical_store_lib.ConversionUtility.integerToByteArray (int value) static
Converts an integer to a byte array.
Parameters
value The integer value to convert.
Returns
The byte array representation of the integer.
Referenced by ce103_hw4_medical_store_lib.Bill.bookToByteArrayBlock(), ce103_hw4_medical_store_lib.Customer.customerToByteArrayBlock(), ce103_hw4_medical_store_lib.Medicine.medicineToByteArrayBlock(), and ce103_hw4_medical_store_lib.Supplier.supplierToByteArrayBlock().
isHex()
static boolean ce103_hw4_medical_store_lib.ConversionUtility.isHex (String str) static
Determines whether a string consists only of hexadecimal digits.
Parameters
str The string to be checked.
Returns
true if the string consists only of hexadecimal digits, false otherwise.
References ce103_hw4_medical_store_lib.ConversionUtility.toByteArray().
stringListToByteArray()
static byte[] ce103_hw4_medical_store_lib.ConversionUtility.stringListToByteArray (List< String > array, int itemMaxCount, int itemMaxLength) static
Converts a list of strings to a byte array.
Parameters
array The list of strings to convert.
itemMaxCount The maximum number of items in the list.
itemMaxLength The maximum length of each item in the list.
Returns
The byte array representation of the list of strings.
stringToByteArray()
static byte[] ce103_hw4_medical_store_lib.ConversionUtility.stringToByteArray (String data) static
Converts a string to a byte array.
Parameters
data The string to convert.
Returns
The byte array representation of the string.
Referenced by ce103_hw4_medical_store_lib.Bill.bookToByteArrayBlock(), ce103_hw4_medical_store_lib.Customer.customerToByteArrayBlock(), ce103_hw4_medical_store_lib.Medicine.medicineToByteArrayBlock(), and ce103_hw4_medical_store_lib.Supplier.supplierToByteArrayBlock().
toAscii()
static String ce103_hw4_medical_store_lib.ConversionUtility.toAscii (String hexString) static
Converts a hexadecimal string to an ASCII string.
Parameters
hexString The hexadecimal string to convert.
Returns
An ASCII string representing the input hexadecimal string.
toByte()
static Byte[] ce103_hw4_medical_store_lib.ConversionUtility.toByte (String hexString) static
Converts a hexadecimal string to an array of bytes.
Parameters
hexString A string containing hexadecimal digits.
Returns
An array of bytes representing the integer values of the hexadecimal digits in the input string.
toByteArray()
static Byte[] ce103_hw4_medical_store_lib.ConversionUtility.toByteArray (String hexString) static
Converts a hexadecimal string to an array of bytes.
Parameters
hexString The hexadecimal string to be converted.
Returns
An array of bytes representing the hexadecimal string.
Referenced by ce103_hw4_medical_store_lib.ConversionUtility.isHex().
toHex()
static String ce103_hw4_medical_store_lib.ConversionUtility.toHex (byte[] arr) static
Converts an array of bytes to a hexadecimal string.
Parameters
arr An array of bytes.
Returns
A hexadecimal string representing the integer values of the bytes in the input array.
The documentation for this class was generated from the following file:
ConversionUtility.java