CE103 Homework 4 Duygu Ayvaz Hayrunnisa Kasimay: ce103_hw4_medical_store_app.InsiderOfTheMenu Class Reference
ce103_hw4_medical_store_app.InsiderOfTheMenu Class Reference
Public Member Functions
int getInput ()
void clear ()
void supplier ()
void listsupp () throws IOException
void listcust () throws IOException
void listmedicine () throws IOException
void stockmedicine () throws IOException
void customer ()
void medicine () throws IOException
void report ()
void addSupplier ()
void addCustomer ()
void editSupplier ()
void editCustomer ()
void purchasemedicine ()
void searchsupp () throws IOException
void searchcust () throws IOException
void salemedicine () throws IOException
Static Public Member Functions
static void mainmenu ()
static void main_box ()
static void box1 ()
static void medicinebox ()
Member Function Documentation
addCustomer()
void ce103_hw4_medical_store_app.InsiderOfTheMenu.addCustomer ()
References ce103_hw4_medical_store_lib.FileUtility.appendBlock(), ce103_hw4_medical_store_app.InsiderOfTheMenu.clear(), ce103_hw4_medical_store_lib.Customer.customerToByteArrayBlock(), ce103_hw4_medical_store_app.InsiderOfTheMenu.main_box(), ce103_hw4_medical_store_lib.Customer.setCity(), ce103_hw4_medical_store_lib.Customer.setEmail(), ce103_hw4_medical_store_lib.Customer.setId(), ce103_hw4_medical_store_lib.Customer.setName(), ce103_hw4_medical_store_lib.Customer.setNum(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.supplier().
Referenced by ce103_hw4_medical_store_app.Menu.performAction().
addSupplier()
void ce103_hw4_medical_store_app.InsiderOfTheMenu.addSupplier ()
References ce103_hw4_medical_store_lib.FileUtility.appendBlock(), ce103_hw4_medical_store_app.InsiderOfTheMenu.clear(), ce103_hw4_medical_store_app.InsiderOfTheMenu.main_box(), ce103_hw4_medical_store_lib.Supplier.setCity(), ce103_hw4_medical_store_lib.Supplier.setContactNo(), ce103_hw4_medical_store_lib.Supplier.setemailID(), ce103_hw4_medical_store_lib.Supplier.setsupplierId(), ce103_hw4_medical_store_lib.Supplier.setsuppliername(), ce103_hw4_medical_store_app.InsiderOfTheMenu.supplier(), and ce103_hw4_medical_store_lib.Supplier.supplierToByteArrayBlock().
Referenced by ce103_hw4_medical_store_app.Menu.performAction().
box1()
static void ce103_hw4_medical_store_app.InsiderOfTheMenu.box1 () static
Referenced by ce103_hw4_medical_store_app.InsiderOfTheMenu.mainmenu().
clear()
void ce103_hw4_medical_store_app.InsiderOfTheMenu.clear ()
Referenced by ce103_hw4_medical_store_app.InsiderOfTheMenu.addCustomer(), ce103_hw4_medical_store_app.InsiderOfTheMenu.addSupplier(), ce103_hw4_medical_store_app.InsiderOfTheMenu.customer(), ce103_hw4_medical_store_app.InsiderOfTheMenu.editCustomer(), ce103_hw4_medical_store_app.InsiderOfTheMenu.editSupplier(), ce103_hw4_medical_store_app.InsiderOfTheMenu.listcust(), ce103_hw4_medical_store_app.InsiderOfTheMenu.listmedicine(), ce103_hw4_medical_store_app.InsiderOfTheMenu.purchasemedicine(), ce103_hw4_medical_store_app.InsiderOfTheMenu.salemedicine(), ce103_hw4_medical_store_app.InsiderOfTheMenu.searchcust(), ce103_hw4_medical_store_app.InsiderOfTheMenu.searchsupp(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.stockmedicine().
customer()
void ce103_hw4_medical_store_app.InsiderOfTheMenu.customer ()
References ce103_hw4_medical_store_app.InsiderOfTheMenu.clear(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.main_box().
Referenced by ce103_hw4_medical_store_app.InsiderOfTheMenu.editCustomer(), ce103_hw4_medical_store_app.InsiderOfTheMenu.listcust(), ce103_hw4_medical_store_app.Menu.performAction(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.searchsupp().
editCustomer()
void ce103_hw4_medical_store_app.InsiderOfTheMenu.editCustomer ()
References ce103_hw4_medical_store_app.InsiderOfTheMenu.clear(), ce103_hw4_medical_store_app.InsiderOfTheMenu.customer(), ce103_hw4_medical_store_lib.Customer.CUSTOMER_DATA_BLOCK_SIZE, ce103_hw4_medical_store_lib.Customer.customerToByteArrayBlock(), ce103_hw4_medical_store_app.InsiderOfTheMenu.main_box(), ce103_hw4_medical_store_lib.Customer.setCity(), ce103_hw4_medical_store_lib.Customer.setEmail(), ce103_hw4_medical_store_lib.Customer.setId(), ce103_hw4_medical_store_lib.Customer.setName(), ce103_hw4_medical_store_lib.Customer.setNum(), and ce103_hw4_medical_store_lib.FileUtility.updateBlock().
Referenced by ce103_hw4_medical_store_app.Menu.performAction().
editSupplier()
void ce103_hw4_medical_store_app.InsiderOfTheMenu.editSupplier ()
References ce103_hw4_medical_store_app.InsiderOfTheMenu.clear(), ce103_hw4_medical_store_app.InsiderOfTheMenu.main_box(), ce103_hw4_medical_store_lib.Supplier.setCity(), ce103_hw4_medical_store_lib.Supplier.setContactNo(), ce103_hw4_medical_store_lib.Supplier.setemailID(), ce103_hw4_medical_store_lib.Supplier.setsupplierId(), ce103_hw4_medical_store_lib.Supplier.setsuppliername(), ce103_hw4_medical_store_lib.Supplier.SUPPLIER_DATA_BLOCK_SIZE, ce103_hw4_medical_store_lib.Supplier.supplierToByteArrayBlock(), and ce103_hw4_medical_store_lib.FileUtility.updateBlock().
Referenced by ce103_hw4_medical_store_app.Menu.performAction().
getInput()
int ce103_hw4_medical_store_app.InsiderOfTheMenu.getInput ()
Referenced by ce103_hw4_medical_store_app.Menu.runMenu().
listcust()
void ce103_hw4_medical_store_app.InsiderOfTheMenu.listcust () throws IOException
References ce103_hw4_medical_store_lib.Customer.ByteArrayBlockToCustomer(), ce103_hw4_medical_store_app.InsiderOfTheMenu.clear(), ce103_hw4_medical_store_app.InsiderOfTheMenu.customer(), ce103_hw4_medical_store_lib.Customer.CUSTOMER_DATA_BLOCK_SIZE, ce103_hw4_medical_store_lib.Customer.getCity(), ce103_hw4_medical_store_lib.Customer.getEmail(), ce103_hw4_medical_store_lib.Customer.getId(), ce103_hw4_medical_store_lib.Customer.getName(), ce103_hw4_medical_store_lib.Customer.getNum(), ce103_hw4_medical_store_app.InsiderOfTheMenu.main_box(), and ce103_hw4_medical_store_lib.FileUtility.readBlock().
Referenced by ce103_hw4_medical_store_app.Menu.performAction().
listmedicine()
void ce103_hw4_medical_store_app.InsiderOfTheMenu.listmedicine () throws IOException
References ce103_hw4_medical_store_lib.Medicine.ByteArrayBlockToMedicine(), ce103_hw4_medical_store_app.InsiderOfTheMenu.clear(), ce103_hw4_medical_store_lib.Medicine.getCabnitno(), ce103_hw4_medical_store_lib.Medicine.getCompanyname(), ce103_hw4_medical_store_lib.Medicine.getExpdate(), ce103_hw4_medical_store_lib.Medicine.getId(), ce103_hw4_medical_store_lib.Medicine.getMedicinename(), ce103_hw4_medical_store_lib.Medicine.getMfgdate(), ce103_hw4_medical_store_lib.Medicine.getQuantity(), ce103_hw4_medical_store_lib.Medicine.getRackno(), ce103_hw4_medical_store_lib.Medicine.getSalecost(), ce103_hw4_medical_store_lib.Medicine.getSuppliername(), ce103_hw4_medical_store_lib.Medicine.getUnitcost(), ce103_hw4_medical_store_app.InsiderOfTheMenu.main_box(), ce103_hw4_medical_store_lib.Medicine.MEDICINE_DATA_BLOCK_SIZE, and ce103_hw4_medical_store_lib.FileUtility.readBlock().
Referenced by ce103_hw4_medical_store_app.Menu.performAction().
listsupp()
void ce103_hw4_medical_store_app.InsiderOfTheMenu.listsupp () throws IOException
References ce103_hw4_medical_store_lib.Supplier.byteArrayBlockToSupplier(), ce103_hw4_medical_store_lib.Supplier.getCity(), ce103_hw4_medical_store_lib.Supplier.getContactNo(), ce103_hw4_medical_store_lib.Supplier.getemailID(), ce103_hw4_medical_store_lib.Supplier.getsupplierId(), ce103_hw4_medical_store_lib.Supplier.getsuppliername(), ce103_hw4_medical_store_app.InsiderOfTheMenu.main_box(), ce103_hw4_medical_store_lib.FileUtility.readBlock(), ce103_hw4_medical_store_app.InsiderOfTheMenu.supplier(), and ce103_hw4_medical_store_lib.Supplier.SUPPLIER_DATA_BLOCK_SIZE.
Referenced by ce103_hw4_medical_store_app.Menu.performAction().
main_box()
static void ce103_hw4_medical_store_app.InsiderOfTheMenu.main_box () static
Referenced by ce103_hw4_medical_store_app.InsiderOfTheMenu.addCustomer(), ce103_hw4_medical_store_app.InsiderOfTheMenu.addSupplier(), ce103_hw4_medical_store_app.InsiderOfTheMenu.customer(), ce103_hw4_medical_store_app.InsiderOfTheMenu.editCustomer(), ce103_hw4_medical_store_app.InsiderOfTheMenu.editSupplier(), ce103_hw4_medical_store_app.InsiderOfTheMenu.listcust(), ce103_hw4_medical_store_app.InsiderOfTheMenu.listmedicine(), ce103_hw4_medical_store_app.InsiderOfTheMenu.listsupp(), ce103_hw4_medical_store_app.InsiderOfTheMenu.mainmenu(), ce103_hw4_medical_store_app.InsiderOfTheMenu.medicine(), ce103_hw4_medical_store_app.InsiderOfTheMenu.purchasemedicine(), ce103_hw4_medical_store_app.InsiderOfTheMenu.report(), ce103_hw4_medical_store_app.InsiderOfTheMenu.salemedicine(), ce103_hw4_medical_store_app.InsiderOfTheMenu.searchcust(), ce103_hw4_medical_store_app.InsiderOfTheMenu.searchsupp(), ce103_hw4_medical_store_app.InsiderOfTheMenu.stockmedicine(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.supplier().
mainmenu()
static void ce103_hw4_medical_store_app.InsiderOfTheMenu.mainmenu () static
References ce103_hw4_medical_store_app.InsiderOfTheMenu.box1(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.main_box().
Referenced by ce103_hw4_medical_store_app.Menu.performAction(), and ce103_hw4_medical_store_app.Menu.printMenu().
medicine()
void ce103_hw4_medical_store_app.InsiderOfTheMenu.medicine () throws IOException
References ce103_hw4_medical_store_app.InsiderOfTheMenu.main_box().
Referenced by ce103_hw4_medical_store_app.Menu.performAction(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.salemedicine().
medicinebox()
static void ce103_hw4_medical_store_app.InsiderOfTheMenu.medicinebox () static
Referenced by ce103_hw4_medical_store_app.InsiderOfTheMenu.salemedicine().
purchasemedicine()
void ce103_hw4_medical_store_app.InsiderOfTheMenu.purchasemedicine ()
References ce103_hw4_medical_store_lib.FileUtility.appendBlock(), ce103_hw4_medical_store_app.InsiderOfTheMenu.clear(), ce103_hw4_medical_store_app.InsiderOfTheMenu.main_box(), ce103_hw4_medical_store_lib.Medicine.medicineToByteArrayBlock(), ce103_hw4_medical_store_lib.Medicine.setCabnitno(), ce103_hw4_medical_store_lib.Medicine.setCompanyname(), ce103_hw4_medical_store_lib.Medicine.setExpdate(), ce103_hw4_medical_store_lib.Medicine.setId(), ce103_hw4_medical_store_lib.Medicine.setMfgdate(), ce103_hw4_medical_store_lib.Medicine.setQuantity(), ce103_hw4_medical_store_lib.Medicine.setRackno(), ce103_hw4_medical_store_lib.Medicine.setSalecost(), ce103_hw4_medical_store_lib.Medicine.setSuppliername(), ce103_hw4_medical_store_lib.Medicine.setUnitcost(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.supplier().
Referenced by ce103_hw4_medical_store_app.Menu.performAction().
report()
void ce103_hw4_medical_store_app.InsiderOfTheMenu.report ()
References ce103_hw4_medical_store_app.InsiderOfTheMenu.main_box().
Referenced by ce103_hw4_medical_store_app.Menu.performAction().
salemedicine()
void ce103_hw4_medical_store_app.InsiderOfTheMenu.salemedicine () throws IOException
References ce103_hw4_medical_store_lib.FileUtility.appendBlock(), ce103_hw4_medical_store_lib.Bill.bookToByteArrayBlock(), ce103_hw4_medical_store_lib.Medicine.ByteArrayBlockToMedicine(), ce103_hw4_medical_store_app.InsiderOfTheMenu.clear(), ce103_hw4_medical_store_lib.Medicine.getCabnitno(), ce103_hw4_medical_store_lib.Medicine.getCompanyname(), ce103_hw4_medical_store_lib.Medicine.getExpdate(), ce103_hw4_medical_store_lib.Medicine.getId(), ce103_hw4_medical_store_lib.Medicine.getMedicinename(), ce103_hw4_medical_store_lib.Medicine.getMfgdate(), ce103_hw4_medical_store_lib.Medicine.getQuantity(), ce103_hw4_medical_store_lib.Medicine.getRackno(), ce103_hw4_medical_store_lib.Medicine.getSalecost(), ce103_hw4_medical_store_lib.Medicine.getSuppliername(), ce103_hw4_medical_store_lib.Medicine.getUnitcost(), ce103_hw4_medical_store_app.InsiderOfTheMenu.main_box(), ce103_hw4_medical_store_app.InsiderOfTheMenu.medicine(), ce103_hw4_medical_store_lib.Medicine.MEDICINE_DATA_BLOCK_SIZE, ce103_hw4_medical_store_app.InsiderOfTheMenu.medicinebox(), ce103_hw4_medical_store_lib.Medicine.medicineToByteArrayBlock(), ce103_hw4_medical_store_lib.FileUtility.readBlock(), ce103_hw4_medical_store_lib.Bill.setBillno(), ce103_hw4_medical_store_lib.Medicine.setCabnitno(), ce103_hw4_medical_store_lib.Medicine.setCompanyname(), ce103_hw4_medical_store_lib.Bill.setcustomername(), ce103_hw4_medical_store_lib.Medicine.setExpdate(), ce103_hw4_medical_store_lib.Medicine.setId(), ce103_hw4_medical_store_lib.Bill.setmedicinename(), ce103_hw4_medical_store_lib.Medicine.setMedicinename(), ce103_hw4_medical_store_lib.Medicine.setMfgdate(), ce103_hw4_medical_store_lib.Medicine.setQuantity(), ce103_hw4_medical_store_lib.Bill.setquantity(), ce103_hw4_medical_store_lib.Medicine.setRackno(), ce103_hw4_medical_store_lib.Bill.setrate(), ce103_hw4_medical_store_lib.Medicine.setSalecost(), ce103_hw4_medical_store_lib.Medicine.setSuppliername(), ce103_hw4_medical_store_lib.Medicine.setUnitcost(), and ce103_hw4_medical_store_lib.FileUtility.updateBlock().
Referenced by ce103_hw4_medical_store_app.Menu.performAction().
searchcust()
void ce103_hw4_medical_store_app.InsiderOfTheMenu.searchcust () throws IOException
References ce103_hw4_medical_store_lib.Customer.ByteArrayBlockToCustomer(), ce103_hw4_medical_store_app.InsiderOfTheMenu.clear(), ce103_hw4_medical_store_lib.Customer.CUSTOMER_DATA_BLOCK_SIZE, ce103_hw4_medical_store_lib.Customer.getCity(), ce103_hw4_medical_store_lib.Customer.getEmail(), ce103_hw4_medical_store_lib.Customer.getId(), ce103_hw4_medical_store_lib.Customer.getName(), ce103_hw4_medical_store_lib.Customer.getNum(), ce103_hw4_medical_store_app.InsiderOfTheMenu.main_box(), ce103_hw4_medical_store_lib.FileUtility.readBlock(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.supplier().
Referenced by ce103_hw4_medical_store_app.Menu.performAction().
searchsupp()
void ce103_hw4_medical_store_app.InsiderOfTheMenu.searchsupp () throws IOException
References ce103_hw4_medical_store_lib.Supplier.byteArrayBlockToSupplier(), ce103_hw4_medical_store_app.InsiderOfTheMenu.clear(), ce103_hw4_medical_store_app.InsiderOfTheMenu.customer(), ce103_hw4_medical_store_lib.Supplier.getCity(), ce103_hw4_medical_store_lib.Supplier.getContactNo(), ce103_hw4_medical_store_lib.Supplier.getemailID(), ce103_hw4_medical_store_lib.Supplier.getsupplierId(), ce103_hw4_medical_store_lib.Supplier.getsuppliername(), ce103_hw4_medical_store_app.InsiderOfTheMenu.main_box(), ce103_hw4_medical_store_lib.FileUtility.readBlock(), and ce103_hw4_medical_store_lib.Supplier.SUPPLIER_DATA_BLOCK_SIZE.
Referenced by ce103_hw4_medical_store_app.Menu.performAction().
stockmedicine()
void ce103_hw4_medical_store_app.InsiderOfTheMenu.stockmedicine () throws IOException
References ce103_hw4_medical_store_lib.Medicine.ByteArrayBlockToMedicine(), ce103_hw4_medical_store_app.InsiderOfTheMenu.clear(), ce103_hw4_medical_store_lib.Medicine.getExpdate(), ce103_hw4_medical_store_lib.Medicine.getId(), ce103_hw4_medical_store_lib.Medicine.getMedicinename(), ce103_hw4_medical_store_lib.Medicine.getQuantity(), ce103_hw4_medical_store_lib.Medicine.getSuppliername(), ce103_hw4_medical_store_app.InsiderOfTheMenu.main_box(), ce103_hw4_medical_store_lib.Medicine.MEDICINE_DATA_BLOCK_SIZE, and ce103_hw4_medical_store_lib.FileUtility.readBlock().
Referenced by ce103_hw4_medical_store_app.Menu.performAction().
supplier()
void ce103_hw4_medical_store_app.InsiderOfTheMenu.supplier ()
References ce103_hw4_medical_store_app.InsiderOfTheMenu.main_box().
Referenced by ce103_hw4_medical_store_app.InsiderOfTheMenu.addCustomer(), ce103_hw4_medical_store_app.InsiderOfTheMenu.addSupplier(), ce103_hw4_medical_store_app.InsiderOfTheMenu.listsupp(), ce103_hw4_medical_store_app.Menu.performAction(), ce103_hw4_medical_store_app.InsiderOfTheMenu.purchasemedicine(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.searchcust().
The documentation for this class was generated from the following file:
InsiderOfTheMenu.java