CE103 Homework 4 Duygu Ayvaz Hayrunnisa Kasimay: ce103_hw4_medical_store_lib.FileUtility Class Reference
ce103_hw4_medical_store_lib.FileUtility Class Reference
Static Public Member Functions
static boolean deleteFile (String path)
static byte[] readBlock (int count, int blockSize, String path) throws IOException
static boolean appendBlock (byte[] data, String path) throws IOException
static boolean updateBlock (byte[] data, int count, int blockSize, String path) throws IOException
static boolean deleteBlock (int count, int blockSize, String path) throws IOException
Member Function Documentation
appendBlock()
static boolean ce103_hw4_medical_store_lib.FileUtility.appendBlock (byte[] data, String path) throws IOException static
Appends a block of data to a file at the specified path.
Parameters
data The data to append to the file.
path The path of the file to append to.
Returns
True if the data was successfully appended to the file, false otherwise.
Exceptions
IOException If an I/O error occurs while writing to the file.
Referenced by ce103_hw4_medical_store_app.InsiderOfTheMenu.addCustomer(), ce103_hw4_medical_store_app.InsiderOfTheMenu.addSupplier(), ce103_hw4_medical_store_app.InsiderOfTheMenu.purchasemedicine(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.salemedicine().
deleteBlock()
static boolean ce103_hw4_medical_store_lib.FileUtility.deleteBlock (int count, int blockSize, String path) throws IOException static
Deletes a block of data from a file at the specified path.
Parameters
count The block number to delete (1-based).
blockSize The size of each block in bytes.
path The path of the file to delete from.
Returns
True if the data was successfully deleted from the file, false otherwise.
Exceptions
IOException If an I/O error occurs while writing to the file.
deleteFile()
static boolean ce103_hw4_medical_store_lib.FileUtility.deleteFile (String path) static
Deletes a file at the specified path.
Parameters
path The path of the file to delete.
Returns
True if the file was successfully deleted, false otherwise.
readBlock()
static byte[] ce103_hw4_medical_store_lib.FileUtility.readBlock (int count, int blockSize, String path) throws IOException static
Reads a block of bytes from a file at the specified path.
Parameters
count The block number to read (1-based).
blockSize The size of each block in bytes.
path The path of the file to read from.
Returns
The byte array containing the block of data read from the file.
Exceptions
IOException If an I/O error occurs while reading the file.
Referenced by ce103_hw4_medical_store_app.InsiderOfTheMenu.listcust(), ce103_hw4_medical_store_app.InsiderOfTheMenu.listmedicine(), ce103_hw4_medical_store_app.InsiderOfTheMenu.listsupp(), ce103_hw4_medical_store_app.InsiderOfTheMenu.salemedicine(), ce103_hw4_medical_store_app.InsiderOfTheMenu.searchcust(), ce103_hw4_medical_store_app.InsiderOfTheMenu.searchsupp(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.stockmedicine().
updateBlock()
static boolean ce103_hw4_medical_store_lib.FileUtility.updateBlock (byte[] data, int count, int blockSize, String path) throws IOException static
Updates a block of data in a file at the specified path.
Parameters
data The data to update in the file.
count The block number to update (1-based).
blockSize The size of each block in bytes.
path The path of the file to update.
Returns
True if the data was successfully updated in the file, false otherwise.
Exceptions
IOException If an I/O error occurs while writing to the file.
Referenced by ce103_hw4_medical_store_app.InsiderOfTheMenu.editCustomer(), ce103_hw4_medical_store_app.InsiderOfTheMenu.editSupplier(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.salemedicine().
The documentation for this class was generated from the following file:
FileUtility.java