CE103 Homework 4 Duygu Ayvaz Hayrunnisa Kasimay: ce103_hw4_medical_store_lib.Supplier Class Reference
ce103_hw4_medical_store_lib.Supplier Class Reference
Public Member Functions
int getsupplierId ()
void setsupplierId (int supplierid)
String getsuppliername ()
void setsuppliername (String suppliername)
String getCity ()
void setCity (String city)
String getContactNo ()
void setContactNo (String contactno)
String getemailID ()
void setemailID (String emailID)
Static Public Member Functions
static byte[] supplierToByteArrayBlock (Supplier supplier)
static Supplier byteArrayBlockToSupplier (byte[] byteArray)
Public Attributes
int _supplierid
String _suppliername
String _city
String _contactno
String _emailID
Static Public Attributes
static final int SUPPLIER_ID_LENGTH = 4
static final int SUPPLIER_NAME_LENGTH = 30
static final int CITY_LENGTH = 30
static final int CONTACT_NO_LENGTH = 30
static final int EMAIL_ID_LENGTH = 30
static final int SUPPLIER_DATA_BLOCK_SIZE
Member Function Documentation
byteArrayBlockToSupplier()
static Supplier ce103_hw4_medical_store_lib.Supplier.byteArrayBlockToSupplier (byte[] byteArray) static
References ce103_hw4_medical_store_lib.ConversionUtility.byteArrayToInteger(), ce103_hw4_medical_store_lib.ConversionUtility.byteArrayToString(), ce103_hw4_medical_store_lib.Supplier.CITY_LENGTH, ce103_hw4_medical_store_lib.Supplier.CONTACT_NO_LENGTH, ce103_hw4_medical_store_lib.Supplier.EMAIL_ID_LENGTH, ce103_hw4_medical_store_lib.Supplier.setCity(), ce103_hw4_medical_store_lib.Supplier.setContactNo(), ce103_hw4_medical_store_lib.Supplier.setemailID(), ce103_hw4_medical_store_lib.Supplier.setsupplierId(), ce103_hw4_medical_store_lib.Supplier.setsuppliername(), ce103_hw4_medical_store_lib.Supplier.SUPPLIER_DATA_BLOCK_SIZE, ce103_hw4_medical_store_lib.Supplier.SUPPLIER_ID_LENGTH, and ce103_hw4_medical_store_lib.Supplier.SUPPLIER_NAME_LENGTH.
Referenced by ce103_hw4_medical_store_app.InsiderOfTheMenu.listsupp(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.searchsupp().
getCity()
String ce103_hw4_medical_store_lib.Supplier.getCity ()
References ce103_hw4_medical_store_lib.Supplier._city.
Referenced by ce103_hw4_medical_store_app.InsiderOfTheMenu.listsupp(), ce103_hw4_medical_store_app.InsiderOfTheMenu.searchsupp(), and ce103_hw4_medical_store_lib.Supplier.supplierToByteArrayBlock().
getContactNo()
String ce103_hw4_medical_store_lib.Supplier.getContactNo ()
References ce103_hw4_medical_store_lib.Supplier._contactno.
Referenced by ce103_hw4_medical_store_app.InsiderOfTheMenu.listsupp(), ce103_hw4_medical_store_app.InsiderOfTheMenu.searchsupp(), and ce103_hw4_medical_store_lib.Supplier.supplierToByteArrayBlock().
getemailID()
String ce103_hw4_medical_store_lib.Supplier.getemailID ()
References ce103_hw4_medical_store_lib.Supplier._emailID.
Referenced by ce103_hw4_medical_store_app.InsiderOfTheMenu.listsupp(), ce103_hw4_medical_store_app.InsiderOfTheMenu.searchsupp(), and ce103_hw4_medical_store_lib.Supplier.supplierToByteArrayBlock().
getsupplierId()
int ce103_hw4_medical_store_lib.Supplier.getsupplierId ()
References ce103_hw4_medical_store_lib.Supplier._supplierid.
Referenced by ce103_hw4_medical_store_app.InsiderOfTheMenu.listsupp(), ce103_hw4_medical_store_app.InsiderOfTheMenu.searchsupp(), and ce103_hw4_medical_store_lib.Supplier.supplierToByteArrayBlock().
getsuppliername()
String ce103_hw4_medical_store_lib.Supplier.getsuppliername ()
References ce103_hw4_medical_store_lib.Supplier._suppliername.
Referenced by ce103_hw4_medical_store_app.InsiderOfTheMenu.listsupp(), ce103_hw4_medical_store_app.InsiderOfTheMenu.searchsupp(), and ce103_hw4_medical_store_lib.Supplier.supplierToByteArrayBlock().
setCity()
void ce103_hw4_medical_store_lib.Supplier.setCity (String city)
Referenced by ce103_hw4_medical_store_app.InsiderOfTheMenu.addSupplier(), ce103_hw4_medical_store_lib.Supplier.byteArrayBlockToSupplier(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.editSupplier().
setContactNo()
void ce103_hw4_medical_store_lib.Supplier.setContactNo (String contactno)
Referenced by ce103_hw4_medical_store_app.InsiderOfTheMenu.addSupplier(), ce103_hw4_medical_store_lib.Supplier.byteArrayBlockToSupplier(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.editSupplier().
setemailID()
void ce103_hw4_medical_store_lib.Supplier.setemailID (String emailID)
Referenced by ce103_hw4_medical_store_app.InsiderOfTheMenu.addSupplier(), ce103_hw4_medical_store_lib.Supplier.byteArrayBlockToSupplier(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.editSupplier().
setsupplierId()
void ce103_hw4_medical_store_lib.Supplier.setsupplierId (int supplierid)
Referenced by ce103_hw4_medical_store_app.InsiderOfTheMenu.addSupplier(), ce103_hw4_medical_store_lib.Supplier.byteArrayBlockToSupplier(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.editSupplier().
setsuppliername()
void ce103_hw4_medical_store_lib.Supplier.setsuppliername (String suppliername)
Referenced by ce103_hw4_medical_store_app.InsiderOfTheMenu.addSupplier(), ce103_hw4_medical_store_lib.Supplier.byteArrayBlockToSupplier(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.editSupplier().
supplierToByteArrayBlock()
static byte[] ce103_hw4_medical_store_lib.Supplier.supplierToByteArrayBlock (Supplier supplier) static
References ce103_hw4_medical_store_lib.Supplier.CITY_LENGTH, ce103_hw4_medical_store_lib.Supplier.CONTACT_NO_LENGTH, ce103_hw4_medical_store_lib.Supplier.EMAIL_ID_LENGTH, ce103_hw4_medical_store_lib.Supplier.getCity(), ce103_hw4_medical_store_lib.Supplier.getContactNo(), ce103_hw4_medical_store_lib.Supplier.getemailID(), ce103_hw4_medical_store_lib.Supplier.getsupplierId(), ce103_hw4_medical_store_lib.Supplier.getsuppliername(), ce103_hw4_medical_store_lib.ConversionUtility.integerToByteArray(), ce103_hw4_medical_store_lib.ConversionUtility.stringToByteArray(), ce103_hw4_medical_store_lib.Supplier.SUPPLIER_DATA_BLOCK_SIZE, ce103_hw4_medical_store_lib.Supplier.SUPPLIER_ID_LENGTH, and ce103_hw4_medical_store_lib.Supplier.SUPPLIER_NAME_LENGTH.
Referenced by ce103_hw4_medical_store_app.InsiderOfTheMenu.addSupplier(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.editSupplier().
Member Data Documentation
_city
String ce103_hw4_medical_store_lib.Supplier._city
Referenced by ce103_hw4_medical_store_lib.Supplier.getCity().
_contactno
String ce103_hw4_medical_store_lib.Supplier._contactno
Referenced by ce103_hw4_medical_store_lib.Supplier.getContactNo().
_emailID
String ce103_hw4_medical_store_lib.Supplier._emailID
Referenced by ce103_hw4_medical_store_lib.Supplier.getemailID().
_supplierid
int ce103_hw4_medical_store_lib.Supplier._supplierid
Referenced by ce103_hw4_medical_store_lib.Supplier.getsupplierId().
_suppliername
String ce103_hw4_medical_store_lib.Supplier._suppliername
Referenced by ce103_hw4_medical_store_lib.Supplier.getsuppliername().
CITY_LENGTH
final int ce103_hw4_medical_store_lib.Supplier.CITY_LENGTH = 30 static
Referenced by ce103_hw4_medical_store_lib.Supplier.byteArrayBlockToSupplier(), and ce103_hw4_medical_store_lib.Supplier.supplierToByteArrayBlock().
CONTACT_NO_LENGTH
final int ce103_hw4_medical_store_lib.Supplier.CONTACT_NO_LENGTH = 30 static
Referenced by ce103_hw4_medical_store_lib.Supplier.byteArrayBlockToSupplier(), and ce103_hw4_medical_store_lib.Supplier.supplierToByteArrayBlock().
EMAIL_ID_LENGTH
final int ce103_hw4_medical_store_lib.Supplier.EMAIL_ID_LENGTH = 30 static
Referenced by ce103_hw4_medical_store_lib.Supplier.byteArrayBlockToSupplier(), and ce103_hw4_medical_store_lib.Supplier.supplierToByteArrayBlock().
SUPPLIER_DATA_BLOCK_SIZE
final int ce103_hw4_medical_store_lib.Supplier.SUPPLIER_DATA_BLOCK_SIZE static
Initial value:
= SUPPLIER_ID_LENGTH +
                                                SUPPLIER_NAME_LENGTH +
                                                CITY_LENGTH +
                                                CONTACT_NO_LENGTH +
                                               EMAIL_ID_LENGTH
Referenced by ce103_hw4_medical_store_lib.Supplier.byteArrayBlockToSupplier(), ce103_hw4_medical_store_app.InsiderOfTheMenu.editSupplier(), ce103_hw4_medical_store_app.InsiderOfTheMenu.listsupp(), ce103_hw4_medical_store_app.InsiderOfTheMenu.searchsupp(), and ce103_hw4_medical_store_lib.Supplier.supplierToByteArrayBlock().
SUPPLIER_ID_LENGTH
final int ce103_hw4_medical_store_lib.Supplier.SUPPLIER_ID_LENGTH = 4 static
Referenced by ce103_hw4_medical_store_lib.Supplier.byteArrayBlockToSupplier(), and ce103_hw4_medical_store_lib.Supplier.supplierToByteArrayBlock().
SUPPLIER_NAME_LENGTH
final int ce103_hw4_medical_store_lib.Supplier.SUPPLIER_NAME_LENGTH = 30 static
Referenced by ce103_hw4_medical_store_lib.Supplier.byteArrayBlockToSupplier(), and ce103_hw4_medical_store_lib.Supplier.supplierToByteArrayBlock().
The documentation for this class was generated from the following file:
Supplier.java