CE103 Homework 4 Duygu Ayvaz Hayrunnisa Kasimay: ce103_hw4_medical_store_lib.Bill Class Reference
ce103_hw4_medical_store_lib.Bill Class Reference
Public Member Functions
String getBillno ()
void setBillno (String Billno)
int getid ()
void setid (int id)
String getmedicinename ()
void setmedicinename (String medicinename)
String getcustomername ()
void setcustomername (String customername)
String getquantity ()
void setquantity (String quantity)
int getrate ()
void setrate (int rate)
Static Public Member Functions
static byte[] bookToByteArrayBlock (Bill book)
static Bill byteArrayBlockToBook (byte[] byteArray)
Static Public Attributes
static final int BILLNO_MAX_LENGTH = 4
static final int ID_MAX_LENGTH = 9
static final int CUSTOMERNAME_MAX_LENGTH = 25
static final int MEDICINENAME_MAX_LENGTH = 25
static final int QUANTITY_MAX_LENGTH = 9
static final int RATE_MAX_LENGTH = 9
static final int Bill_DATA_BLOCK_SIZE = BILLNO_MAX_LENGTH + CUSTOMERNAME_MAX_LENGTH + MEDICINENAME_MAX_LENGTH + QUANTITY_MAX_LENGTH + RATE_MAX_LENGTH + ID_MAX_LENGTH
Member Function Documentation
bookToByteArrayBlock()
static byte[] ce103_hw4_medical_store_lib.Bill.bookToByteArrayBlock (Bill book) static
References ce103_hw4_medical_store_lib.Bill.Bill_DATA_BLOCK_SIZE, ce103_hw4_medical_store_lib.Bill.BILLNO_MAX_LENGTH, ce103_hw4_medical_store_lib.Bill.CUSTOMERNAME_MAX_LENGTH, ce103_hw4_medical_store_lib.Bill.getBillno(), ce103_hw4_medical_store_lib.Bill.getcustomername(), ce103_hw4_medical_store_lib.Bill.getid(), ce103_hw4_medical_store_lib.Bill.getmedicinename(), ce103_hw4_medical_store_lib.Bill.getquantity(), ce103_hw4_medical_store_lib.Bill.getrate(), ce103_hw4_medical_store_lib.Bill.ID_MAX_LENGTH, ce103_hw4_medical_store_lib.ConversionUtility.integerToByteArray(), ce103_hw4_medical_store_lib.Bill.MEDICINENAME_MAX_LENGTH, ce103_hw4_medical_store_lib.Bill.QUANTITY_MAX_LENGTH, ce103_hw4_medical_store_lib.Bill.RATE_MAX_LENGTH, and ce103_hw4_medical_store_lib.ConversionUtility.stringToByteArray().
Referenced by ce103_hw4_medical_store_app.InsiderOfTheMenu.salemedicine().
byteArrayBlockToBook()
static Bill ce103_hw4_medical_store_lib.Bill.byteArrayBlockToBook (byte[] byteArray) static
References ce103_hw4_medical_store_lib.Bill.Bill_DATA_BLOCK_SIZE, ce103_hw4_medical_store_lib.Bill.BILLNO_MAX_LENGTH, ce103_hw4_medical_store_lib.ConversionUtility.byteArrayToInteger(), ce103_hw4_medical_store_lib.ConversionUtility.byteArrayToString(), ce103_hw4_medical_store_lib.Bill.CUSTOMERNAME_MAX_LENGTH, ce103_hw4_medical_store_lib.Bill.ID_MAX_LENGTH, ce103_hw4_medical_store_lib.Bill.MEDICINENAME_MAX_LENGTH, ce103_hw4_medical_store_lib.Bill.QUANTITY_MAX_LENGTH, ce103_hw4_medical_store_lib.Bill.RATE_MAX_LENGTH, ce103_hw4_medical_store_lib.Bill.setBillno(), ce103_hw4_medical_store_lib.Bill.setcustomername(), ce103_hw4_medical_store_lib.Bill.setid(), ce103_hw4_medical_store_lib.Bill.setmedicinename(), ce103_hw4_medical_store_lib.Bill.setquantity(), and ce103_hw4_medical_store_lib.Bill.setrate().
getBillno()
String ce103_hw4_medical_store_lib.Bill.getBillno ()
Referenced by ce103_hw4_medical_store_lib.Bill.bookToByteArrayBlock().
getcustomername()
String ce103_hw4_medical_store_lib.Bill.getcustomername ()
Referenced by ce103_hw4_medical_store_lib.Bill.bookToByteArrayBlock().
getid()
int ce103_hw4_medical_store_lib.Bill.getid ()
Referenced by ce103_hw4_medical_store_lib.Bill.bookToByteArrayBlock().
getmedicinename()
String ce103_hw4_medical_store_lib.Bill.getmedicinename ()
Referenced by ce103_hw4_medical_store_lib.Bill.bookToByteArrayBlock().
getquantity()
String ce103_hw4_medical_store_lib.Bill.getquantity ()
Referenced by ce103_hw4_medical_store_lib.Bill.bookToByteArrayBlock().
getrate()
int ce103_hw4_medical_store_lib.Bill.getrate ()
Referenced by ce103_hw4_medical_store_lib.Bill.bookToByteArrayBlock().
setBillno()
void ce103_hw4_medical_store_lib.Bill.setBillno (String Billno)
Referenced by ce103_hw4_medical_store_lib.Bill.byteArrayBlockToBook(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.salemedicine().
setcustomername()
void ce103_hw4_medical_store_lib.Bill.setcustomername (String customername)
Referenced by ce103_hw4_medical_store_lib.Bill.byteArrayBlockToBook(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.salemedicine().
setid()
void ce103_hw4_medical_store_lib.Bill.setid (int id)
Referenced by ce103_hw4_medical_store_lib.Bill.byteArrayBlockToBook().
setmedicinename()
void ce103_hw4_medical_store_lib.Bill.setmedicinename (String medicinename)
Referenced by ce103_hw4_medical_store_lib.Bill.byteArrayBlockToBook(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.salemedicine().
setquantity()
void ce103_hw4_medical_store_lib.Bill.setquantity (String quantity)
Referenced by ce103_hw4_medical_store_lib.Bill.byteArrayBlockToBook(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.salemedicine().
setrate()
void ce103_hw4_medical_store_lib.Bill.setrate (int rate)
Referenced by ce103_hw4_medical_store_lib.Bill.byteArrayBlockToBook(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.salemedicine().
Member Data Documentation
Bill_DATA_BLOCK_SIZE
final int ce103_hw4_medical_store_lib.Bill.Bill_DATA_BLOCK_SIZE = BILLNO_MAX_LENGTH + CUSTOMERNAME_MAX_LENGTH + MEDICINENAME_MAX_LENGTH + QUANTITY_MAX_LENGTH + RATE_MAX_LENGTH + ID_MAX_LENGTH static
Referenced by ce103_hw4_medical_store_lib.Bill.bookToByteArrayBlock(), and ce103_hw4_medical_store_lib.Bill.byteArrayBlockToBook().
BILLNO_MAX_LENGTH
final int ce103_hw4_medical_store_lib.Bill.BILLNO_MAX_LENGTH = 4 static
Referenced by ce103_hw4_medical_store_lib.Bill.bookToByteArrayBlock(), and ce103_hw4_medical_store_lib.Bill.byteArrayBlockToBook().
CUSTOMERNAME_MAX_LENGTH
final int ce103_hw4_medical_store_lib.Bill.CUSTOMERNAME_MAX_LENGTH = 25 static
Referenced by ce103_hw4_medical_store_lib.Bill.bookToByteArrayBlock(), and ce103_hw4_medical_store_lib.Bill.byteArrayBlockToBook().
ID_MAX_LENGTH
final int ce103_hw4_medical_store_lib.Bill.ID_MAX_LENGTH = 9 static
Referenced by ce103_hw4_medical_store_lib.Bill.bookToByteArrayBlock(), and ce103_hw4_medical_store_lib.Bill.byteArrayBlockToBook().
MEDICINENAME_MAX_LENGTH
final int ce103_hw4_medical_store_lib.Bill.MEDICINENAME_MAX_LENGTH = 25 static
Referenced by ce103_hw4_medical_store_lib.Bill.bookToByteArrayBlock(), and ce103_hw4_medical_store_lib.Bill.byteArrayBlockToBook().
QUANTITY_MAX_LENGTH
final int ce103_hw4_medical_store_lib.Bill.QUANTITY_MAX_LENGTH = 9 static
Referenced by ce103_hw4_medical_store_lib.Bill.bookToByteArrayBlock(), and ce103_hw4_medical_store_lib.Bill.byteArrayBlockToBook().
RATE_MAX_LENGTH
final int ce103_hw4_medical_store_lib.Bill.RATE_MAX_LENGTH = 9 static
Referenced by ce103_hw4_medical_store_lib.Bill.bookToByteArrayBlock(), and ce103_hw4_medical_store_lib.Bill.byteArrayBlockToBook().
The documentation for this class was generated from the following file:
Bill.java