CE103 Homework 4 Duygu Ayvaz Hayrunnisa Kasimay: ce103_hw4_medical_store_app.Menu Class Reference
ce103_hw4_medical_store_app.Menu Class Reference
Public Member Functions
void runMenu () throws IOException
void clearScreen ()
void printMenu ()
void performAction (int choice) throws IOException
Static Public Member Functions
static void main (String[] args) throws IOException
Member Function Documentation
clearScreen()
void ce103_hw4_medical_store_app.Menu.clearScreen ()
Referenced by ce103_hw4_medical_store_app.Menu.performAction(), and ce103_hw4_medical_store_app.Menu.printMenu().
main()
static void ce103_hw4_medical_store_app.Menu.main (String[] args) throws IOException static
References ce103_hw4_medical_store_app.Menu.runMenu().
performAction()
void ce103_hw4_medical_store_app.Menu.performAction (int choice) throws IOException
References ce103_hw4_medical_store_app.InsiderOfTheMenu.addCustomer(), ce103_hw4_medical_store_app.InsiderOfTheMenu.addSupplier(), ce103_hw4_medical_store_app.Menu.clearScreen(), ce103_hw4_medical_store_app.InsiderOfTheMenu.customer(), ce103_hw4_medical_store_app.InsiderOfTheMenu.editCustomer(), ce103_hw4_medical_store_app.InsiderOfTheMenu.editSupplier(), ce103_hw4_medical_store_app.InsiderOfTheMenu.listcust(), ce103_hw4_medical_store_app.InsiderOfTheMenu.listmedicine(), ce103_hw4_medical_store_app.InsiderOfTheMenu.listsupp(), ce103_hw4_medical_store_app.InsiderOfTheMenu.mainmenu(), ce103_hw4_medical_store_app.InsiderOfTheMenu.medicine(), ce103_hw4_medical_store_app.Menu.printMenu(), ce103_hw4_medical_store_app.InsiderOfTheMenu.purchasemedicine(), ce103_hw4_medical_store_app.InsiderOfTheMenu.report(), ce103_hw4_medical_store_app.InsiderOfTheMenu.salemedicine(), ce103_hw4_medical_store_app.InsiderOfTheMenu.searchcust(), ce103_hw4_medical_store_app.InsiderOfTheMenu.searchsupp(), ce103_hw4_medical_store_app.InsiderOfTheMenu.stockmedicine(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.supplier().
Referenced by ce103_hw4_medical_store_app.Menu.runMenu().
printMenu()
void ce103_hw4_medical_store_app.Menu.printMenu ()
References ce103_hw4_medical_store_app.Menu.clearScreen(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.mainmenu().
Referenced by ce103_hw4_medical_store_app.Menu.performAction(), and ce103_hw4_medical_store_app.Menu.runMenu().
runMenu()
void ce103_hw4_medical_store_app.Menu.runMenu () throws IOException
References ce103_hw4_medical_store_app.InsiderOfTheMenu.getInput(), ce103_hw4_medical_store_app.Menu.performAction(), and ce103_hw4_medical_store_app.Menu.printMenu().
Referenced by ce103_hw4_medical_store_app.Menu.main().
The documentation for this class was generated from the following file:
Menu.java