CE103 Homework 4 Duygu Ayvaz Hayrunnisa Kasimay: ce103_hw4_medical_store_lib.Customer Class Reference
ce103_hw4_medical_store_lib.Customer Class Reference
Public Member Functions
int getId ()
void setId (int id)
String getName ()
void setName (String name)
String getCity ()
void setCity (String city)
String getNum ()
void setNum (String num)
String getEmail ()
void setEmail (String emailID)
Static Public Member Functions
static byte[] customerToByteArrayBlock (Customer customer)
static Customer ByteArrayBlockToCustomer (byte[] byteArray)
Static Public Attributes
static final int ID_LENGTH = 4
static final int NAME_LENGTH = 100
static final int CITY_LENGTH = 50
static final int NUM_LENGTH = 30
static final int EMAIL_LENGTH = 50
static final int CUSTOMER_DATA_BLOCK_SIZE = ID_LENGTH + NAME_LENGTH + CITY_LENGTH + NUM_LENGTH + EMAIL_LENGTH
Member Function Documentation
ByteArrayBlockToCustomer()
static Customer ce103_hw4_medical_store_lib.Customer.ByteArrayBlockToCustomer (byte[] byteArray) static
References ce103_hw4_medical_store_lib.ConversionUtility.byteArrayToInteger(), ce103_hw4_medical_store_lib.ConversionUtility.byteArrayToString(), ce103_hw4_medical_store_lib.Customer.CITY_LENGTH, ce103_hw4_medical_store_lib.Customer.CUSTOMER_DATA_BLOCK_SIZE, ce103_hw4_medical_store_lib.Customer.EMAIL_LENGTH, ce103_hw4_medical_store_lib.Customer.ID_LENGTH, ce103_hw4_medical_store_lib.Customer.NAME_LENGTH, ce103_hw4_medical_store_lib.Customer.NUM_LENGTH, ce103_hw4_medical_store_lib.Customer.setCity(), ce103_hw4_medical_store_lib.Customer.setEmail(), ce103_hw4_medical_store_lib.Customer.setId(), ce103_hw4_medical_store_lib.Customer.setName(), and ce103_hw4_medical_store_lib.Customer.setNum().
Referenced by ce103_hw4_medical_store_app.InsiderOfTheMenu.listcust(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.searchcust().
customerToByteArrayBlock()
static byte[] ce103_hw4_medical_store_lib.Customer.customerToByteArrayBlock (Customer customer) static
References ce103_hw4_medical_store_lib.Customer.CITY_LENGTH, ce103_hw4_medical_store_lib.Customer.CUSTOMER_DATA_BLOCK_SIZE, ce103_hw4_medical_store_lib.Customer.EMAIL_LENGTH, ce103_hw4_medical_store_lib.Customer.getCity(), ce103_hw4_medical_store_lib.Customer.getEmail(), ce103_hw4_medical_store_lib.Customer.getId(), ce103_hw4_medical_store_lib.Customer.getName(), ce103_hw4_medical_store_lib.Customer.getNum(), ce103_hw4_medical_store_lib.Customer.ID_LENGTH, ce103_hw4_medical_store_lib.ConversionUtility.integerToByteArray(), ce103_hw4_medical_store_lib.Customer.NAME_LENGTH, ce103_hw4_medical_store_lib.Customer.NUM_LENGTH, and ce103_hw4_medical_store_lib.ConversionUtility.stringToByteArray().
Referenced by ce103_hw4_medical_store_app.InsiderOfTheMenu.addCustomer(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.editCustomer().
getCity()
String ce103_hw4_medical_store_lib.Customer.getCity ()
Referenced by ce103_hw4_medical_store_lib.Customer.customerToByteArrayBlock(), ce103_hw4_medical_store_app.InsiderOfTheMenu.listcust(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.searchcust().
getEmail()
String ce103_hw4_medical_store_lib.Customer.getEmail ()
Referenced by ce103_hw4_medical_store_lib.Customer.customerToByteArrayBlock(), ce103_hw4_medical_store_app.InsiderOfTheMenu.listcust(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.searchcust().
getId()
int ce103_hw4_medical_store_lib.Customer.getId ()
Referenced by ce103_hw4_medical_store_lib.Customer.customerToByteArrayBlock(), ce103_hw4_medical_store_app.InsiderOfTheMenu.listcust(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.searchcust().
getName()
String ce103_hw4_medical_store_lib.Customer.getName ()
Referenced by ce103_hw4_medical_store_lib.Customer.customerToByteArrayBlock(), ce103_hw4_medical_store_app.InsiderOfTheMenu.listcust(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.searchcust().
getNum()
String ce103_hw4_medical_store_lib.Customer.getNum ()
Referenced by ce103_hw4_medical_store_lib.Customer.customerToByteArrayBlock(), ce103_hw4_medical_store_app.InsiderOfTheMenu.listcust(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.searchcust().
setCity()
void ce103_hw4_medical_store_lib.Customer.setCity (String city)
Referenced by ce103_hw4_medical_store_app.InsiderOfTheMenu.addCustomer(), ce103_hw4_medical_store_lib.Customer.ByteArrayBlockToCustomer(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.editCustomer().
setEmail()
void ce103_hw4_medical_store_lib.Customer.setEmail (String emailID)
Referenced by ce103_hw4_medical_store_app.InsiderOfTheMenu.addCustomer(), ce103_hw4_medical_store_lib.Customer.ByteArrayBlockToCustomer(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.editCustomer().
setId()
void ce103_hw4_medical_store_lib.Customer.setId (int id)
Referenced by ce103_hw4_medical_store_app.InsiderOfTheMenu.addCustomer(), ce103_hw4_medical_store_lib.Customer.ByteArrayBlockToCustomer(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.editCustomer().
setName()
void ce103_hw4_medical_store_lib.Customer.setName (String name)
Referenced by ce103_hw4_medical_store_app.InsiderOfTheMenu.addCustomer(), ce103_hw4_medical_store_lib.Customer.ByteArrayBlockToCustomer(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.editCustomer().
setNum()
void ce103_hw4_medical_store_lib.Customer.setNum (String num)
Referenced by ce103_hw4_medical_store_app.InsiderOfTheMenu.addCustomer(), ce103_hw4_medical_store_lib.Customer.ByteArrayBlockToCustomer(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.editCustomer().
Member Data Documentation
CITY_LENGTH
final int ce103_hw4_medical_store_lib.Customer.CITY_LENGTH = 50 static
Referenced by ce103_hw4_medical_store_lib.Customer.ByteArrayBlockToCustomer(), and ce103_hw4_medical_store_lib.Customer.customerToByteArrayBlock().
CUSTOMER_DATA_BLOCK_SIZE
final int ce103_hw4_medical_store_lib.Customer.CUSTOMER_DATA_BLOCK_SIZE = ID_LENGTH + NAME_LENGTH + CITY_LENGTH + NUM_LENGTH + EMAIL_LENGTH static
Referenced by ce103_hw4_medical_store_lib.Customer.ByteArrayBlockToCustomer(), ce103_hw4_medical_store_lib.Customer.customerToByteArrayBlock(), ce103_hw4_medical_store_app.InsiderOfTheMenu.editCustomer(), ce103_hw4_medical_store_app.InsiderOfTheMenu.listcust(), and ce103_hw4_medical_store_app.InsiderOfTheMenu.searchcust().
EMAIL_LENGTH
final int ce103_hw4_medical_store_lib.Customer.EMAIL_LENGTH = 50 static
Referenced by ce103_hw4_medical_store_lib.Customer.ByteArrayBlockToCustomer(), and ce103_hw4_medical_store_lib.Customer.customerToByteArrayBlock().
ID_LENGTH
final int ce103_hw4_medical_store_lib.Customer.ID_LENGTH = 4 static
Referenced by ce103_hw4_medical_store_lib.Customer.ByteArrayBlockToCustomer(), and ce103_hw4_medical_store_lib.Customer.customerToByteArrayBlock().
NAME_LENGTH
final int ce103_hw4_medical_store_lib.Customer.NAME_LENGTH = 100 static
Referenced by ce103_hw4_medical_store_lib.Customer.ByteArrayBlockToCustomer(), and ce103_hw4_medical_store_lib.Customer.customerToByteArrayBlock().
NUM_LENGTH
final int ce103_hw4_medical_store_lib.Customer.NUM_LENGTH = 30 static
Referenced by ce103_hw4_medical_store_lib.Customer.ByteArrayBlockToCustomer(), and ce103_hw4_medical_store_lib.Customer.customerToByteArrayBlock().
The documentation for this class was generated from the following file:
Customer.java